## Demo 04: Using Python to Interact with Data in Files
It is a common requirement to interact with data located on various storage devices (e.g., local hard drives, corporate network-available storage devices & storage area networks (SAN's), cloud-based storage, (DataLakes)). File-based data may be stored in a variety of formats including: plain text, tab-separated values, comma-separated values, JSON (JavaScript Object Notation), XML (eXtensible Markup Language), as well as binary document filetypes, audio-visual filetypes. This demonstration illustrates methods for interacting with some of these data formats as they are written to, and read from, various text-based files.

Since we must leverage the underlying Operating System to gain access to any storage devices, local or network-available, we will first **import** the appropriate **os** library.

In [1]:
import os

### 1.0. Interacting with Text Files
#### 1.1. Writing a List to a Text File

In [2]:
# Create a list to hold some agenda items.
agenda = ["Wake Up at 6:30 AM",
          "Stretch and exercise",
          "Take a shower",
          "Eat breakfast",
          "Read about Python programming"
         ]

# Specify a location for creating the new text file.
data_dir = os.path.join(os.getcwd(), 'data')
agenda_file = os.path.join(data_dir, 'agenda_entries.txt')

# Open the new file, in write mode, to capture the new data.
file = open(agenda_file, "w") # 'w'=write mode, 'r'=read mode, 'a'=append mode

# Write the contents of the list to the file.
file.write("\n".join(agenda))

# The file must be 'closed' to save the appended data.
file.close()

#### 1.2. Reading Data from the Newly Created Text File

In [3]:
# Open the new file, in read mode, to access the data.
file = open(agenda_file, "r")  # 'r'=read mode
content = file.read()
file.close()

print(content)

Wake Up at 6:30 AM
Stretch and exercise
Take a shower
Eat breakfast
Read about Python programming

#### 1.3. Appending Data to an Existing Text File

In [4]:
# Create some additional agenda items
new_agenda_items = ["Commute to Work",
                    "Get Coffee with a Coworker",
                    "Start a New Python Project",
                    "Do Some Python Research"
                   ]

# Specify the location of the existing text file.
agenda_file = os.path.join(data_dir, 'agenda_entries.txt')

# Open the existing file, in append mode, to capture the new items.
file = open(agenda_file, 'a')  # 'a'=append mode

# Write the contents of the list to the file.
file.write("\n" + "\n".join(new_agenda_items))

# The file must be 'closed' to save the appended data.
file.close()

#### 1.4. Read New Data from the Text File

In [5]:
# Open the new file, in read mode, to access the data.
file = open(agenda_file, "r")  # 'r'=read mode
content = file.read()
file.close()

# Verify the additional agenda items in the file
print(content)

Wake Up at 6:30 AM
Stretch and exercise
Take a shower
Eat breakfast
Read about Python programming
Commute to Work
Get Coffee with a Coworker
Start a New Python Project
Do Some Python Research

#### 1.5. Find Entries Containing 'Python' and Write them to a New Text File

In [6]:
# Open the new file, in read mode, to access the data.
with open(agenda_file, "r") as file:
    entries = file.read().split("\n")

python_entries = []
for entry in entries:
    if "Python" in entry:
        python_entries.append(entry)

# Specify a location for creating the new text file.
python_agenda_file = os.path.join(data_dir, 'python_agenda_entries.txt')

# Open the new file, in write mode, to capture the new data.
with open(python_agenda_file, "w") as file:
    # Write the contents of the list to the file.
    file.write("\n".join(python_entries))

# Open the new file, in read mode, to verify the data.
with open(python_agenda_file, "r") as file:
    print(file.read())

Read about Python programming
Start a New Python Project
Do Some Python Research

### 2.0. Writing a List of Dictionaries to a New File
The previous demonstration illustrated writing and reading very simple data to a plain text file; however, it is far more common to interact with data stored in one of the semantically self-describing data formats like comma-separated values (CSV), or JavaScript Object Notation (JSON). Building on the previous example, this demonstration will illustrate how to interact with these storage formats using the appropriate data transformation techniques and file types (MIME's).

#### 2.1. Create a List of Dictionaries to Hold Some Agenda Items
Dictionaries are a very commonly implemented data structure. They store data in a semantically self-describing format, and they provide the basis for the JavaScript Object Notation (JSON) format. Multi-line JSON files store multiple dictionaries contained within a List, and are a very common data structure for persisting tabular data to data files.

In [7]:
agenda = [
    {
        "agenda_id" : 1,
        "activity" : "Wake Up",
        "time" : "6:30 AM"
    },
    {
        "agenda_id" : 2,
        "activity" : "Stretch and exercise",
        "time" : "6:35 AM"
    },
    {
        "agenda_id" : 3,
        "activity" : "Take a shower",
        "time" : "6:50 AM"
    },
    {
        "agenda_id" : 4,
        "activity" : "Eat breakfast",
        "time" : "7:15 AM"
    },
    {
        "agenda_id" : 5,
        "activity" : "Read about Python programming",
        "time" : "8:00 AM"
    }
]

#### 2.2. Convert the List of Dictionaries to Comma-Separated Values and Write Them to a CSV File
Historically, another very popular data interchange format is comma-separated values (CSV) because it is leveraged by so many applications used to input, store and represent tabular data. It is commonly used by spreadsheet applications like Microsoft Excel, but is even more broadly adopted as a data storage and interchange format, and is used extensively with data extract-transform-load (ETL) pipeline processes.

In [8]:
# Specify a location for creating the new text file.
data_dir = os.path.join(os.getcwd(), 'data')
agenda_csv_file = os.path.join(data_dir, 'agenda_entries.csv')

# Open the new file, in write mode, to capture the new data.
file = open(agenda_csv_file, "w") # 'w'=write mode, 'r'=read mode, 'a'=append mode

# Write the contents of the list of dictionaries to the file in CSV format with headers.
file.write("\n".join([",".join([f"{value}" for value in d.values()]) for d in [dict(zip(agenda[0], agenda[0].keys()))] + agenda]))

# The file must be 'closed' to save the appended data.
file.close()

#### 2.3. Reading from the Newly Created CSV File

In [9]:
# Open the new file, in read mode, to access the data.
file = open(agenda_csv_file, "r")  # 'r'=read mode
content = file.read()
file.close()

print(content)

agenda_id,activity,time
1,Wake Up,6:30 AM
2,Stretch and exercise,6:35 AM
3,Take a shower,6:50 AM
4,Eat breakfast,7:15 AM
5,Read about Python programming,8:00 AM

This validates that the data extracted from the list of dictioneries was successfully translated from its native JavaScript Object Notation to comma-separated values. Either of these are actually interchange formats that preserve the semantic context along with the data.

#### 2.4. Appending Data to an Existing CSV File

In [10]:
# Create some additional agenda items
agenda = [
    {
        "agenda_id" : 6,
        "activity" : "Commute to Work",
        "time" : "8:30 AM"
    },
    {
        "agenda_id" : 7,
        "activity" : "Get Coffee with a Coworker",
        "time" : "9:00 AM"
    },
    {
        "agenda_id" : 8,
        "activity" : "Start a New Python Project",
        "time" : "9:15 AM"
    },
    {
        "agenda_id" : 9,
        "activity" : "Do Some Python Research",
        "time" : "9:45 AM"
    }
]

# Specify the location of the existing CSV file.
agenda_csv_file = os.path.join(data_dir, 'agenda_entries.csv')

# Open the existing file, in append mode, to capture the new items.
file = open(agenda_csv_file, 'a')  # 'a'=append mode

# Write the contents of the list of dictionaries to the file in CSV format without headers.
file.write("\n" + "\n".join([','.join([f"{v}" for v in d.values()]) for d in agenda]))

# The file must be 'closed' to save the appended data.
file.close()

#### 2.5. Read Newly Added Data From the CSV File

In [11]:
# Open the new file, in read mode, to access the data.
file = open(agenda_csv_file, "r")  # 'r'=read mode
content = file.read()
file.close()

print(content)

agenda_id,activity,time
1,Wake Up,6:30 AM
2,Stretch and exercise,6:35 AM
3,Take a shower,6:50 AM
4,Eat breakfast,7:15 AM
5,Read about Python programming,8:00 AM
6,Commute to Work,8:30 AM
7,Get Coffee with a Coworker,9:00 AM
8,Start a New Python Project,9:15 AM
9,Do Some Python Research,9:45 AM

### 3.0. Working with JavaScript Object Notation (JSON) Data
In our previous example we illustrated how fundamental Python data constructs like the Dictionary and the List can be used to represent textual data in a semantically self-describing, semi-structured format that enables for nesting data structures and polyschematism. While we could certainly write the data to a file using native Python language elements, these tasks are more commonly accomplished using libraries like <b>json</b> and <b>csv</b>. The next demonstration will illustrate using the <b>Pandas</b> library to accomplish similar interchange tasks, but at a higher level of abstraction.
<p>To that end, first we must import the <b>json</b> and <b>csv</b> libraries.

In [12]:
import json
import csv

#### 3.1. Extract Data from a CSV File

In [13]:
# Specify the location of the existing CSV file.
agenda_csv_file = os.path.join(data_dir, 'agenda_entries.csv')

# Open the CSV file, read its contents, and convert its rows to dictionaries
with open(agenda_csv_file, mode='r', newline='', encoding='utf-8') as csvfile:
    data = list(csv.DictReader(csvfile))

#### 3.2. Write the Transformed CSV Data to a JSON File

In [14]:
# Specify the location of the new JSON file
agenda_json_file = os.path.join(data_dir, 'agenda_entries.json')

# Serialize the data with indentation, and then write it to a JSON file.
with open(agenda_json_file, mode='w', encoding='utf-8') as jsonfile:
   json.dump(data, jsonfile, indent=4)

#### 3.3. Read the Data from the JSON File and Display Its File Formatting

In [15]:
# Open the new file, in read mode, to access the data.
file = open(agenda_json_file, "r")  # 'r'=read mode
content = file.read()
file.close()

print(content)

[
    {
        "agenda_id": "1",
        "activity": "Wake Up",
        "time": "6:30 AM"
    },
    {
        "agenda_id": "2",
        "activity": "Stretch and exercise",
        "time": "6:35 AM"
    },
    {
        "agenda_id": "3",
        "activity": "Take a shower",
        "time": "6:50 AM"
    },
    {
        "agenda_id": "4",
        "activity": "Eat breakfast",
        "time": "7:15 AM"
    },
    {
        "agenda_id": "5",
        "activity": "Read about Python programming",
        "time": "8:00 AM"
    },
    {
        "agenda_id": "6",
        "activity": "Commute to Work",
        "time": "8:30 AM"
    },
    {
        "agenda_id": "7",
        "activity": "Get Coffee with a Coworker",
        "time": "9:00 AM"
    },
    {
        "agenda_id": "8",
        "activity": "Start a New Python Project",
        "time": "9:15 AM"
    },
    {
        "agenda_id": "9",
        "activity": "Do Some Python Research",
        "time": "9:45 AM"
    }
]

### 4.0. Using Pandas to Interact with Data Files
The <a href="https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.read_csv.html#pandas.read_csv"><b>Pandas API</b></a> includes several functions that enable interacting with data in various file formats.  These include `read_csv()` & `to_csv()`, `read_excel()` & `to_excel()`, `read_html()` & `to_html()`, `read_json()` & `to_json()`, and `read_xml()` & `to_xml()`... to name a few. What's more, this library provides critical functionality that enables textual data to be manipulated as a tabular object... similar to that of a spreadsheet application.

The following demonstration will illustrate the pattern common to file interaction with these functions using the comma-separated values (CSV) file format as an example.

#### 4.1. Load Data from a CSV File

In [16]:
import pandas as pd

data_dir = os.path.join(os.getcwd(), 'data')
data_file = os.path.join(data_dir, 'northwind_products.csv')

df = pd.read_csv(data_file, header=0, index_col=0)
df.head()

,supplier_ids,id,product_code,product_name,description,standard_cost,list_price,reorder_level,target_level,quantity_per_unit,discontinued,minimum_reorder_quantity,category,attachments
0,4,1,NWTB-1,Northwind Traders Chai,NaN,13.5000,18.00,10,40,10 boxes x 20 bags,0,10.0,Beverages,b''
1,10,3,NWTCO-3,Northwind Traders Syrup,NaN,7.5000,10.00,25,100,12 - 550 ml bottles,0,25.0,Condiments,b''
2,10,4,NWTCO-4,Northwind Traders Cajun Seasoning,NaN,16.5000,22.00,10,40,48 - 6 oz jars,0,10.0,Condiments,b''
3,10,5,NWTO-5,Northwind Traders Olive Oil,NaN,16.0125,21.35,10,40,36 boxes,0,10.0,Oil,b''
4,2;6,6,NWTJP-6,Northwind Traders Boysenberry Spread,NaN,18.7500,25.00,25,100,12 - 8 oz jars,0,25.0,"Jams, Preserves",b''

#### 2.2. Drop Unimportant Features

In [17]:
df.drop(['description','attachments'], axis=1, inplace=True)
df.columns

Index(['supplier_ids', 'id', 'product_code', 'product_name', 'standard_cost',
       'list_price', 'reorder_level', 'target_level', 'quantity_per_unit',
       'discontinued', 'minimum_reorder_quantity', 'category'],
      dtype='object')

#### 2.3. Add a New Feature Using a Map (Dictionary) to Assign New Values

In [18]:
df['discontinued_desc'] = df.discontinued.map({1: 'True', 0: 'False'})
df.head()

,supplier_ids,id,product_code,product_name,standard_cost,list_price,reorder_level,target_level,quantity_per_unit,discontinued,minimum_reorder_quantity,category,discontinued_desc
0,4,1,NWTB-1,Northwind Traders Chai,13.5000,18.00,10,40,10 boxes x 20 bags,0,10.0,Beverages,False
1,10,3,NWTCO-3,Northwind Traders Syrup,7.5000,10.00,25,100,12 - 550 ml bottles,0,25.0,Condiments,False
2,10,4,NWTCO-4,Northwind Traders Cajun Seasoning,16.5000,22.00,10,40,48 - 6 oz jars,0,10.0,Condiments,False
3,10,5,NWTO-5,Northwind Traders Olive Oil,16.0125,21.35,10,40,36 boxes,0,10.0,Oil,False
4,2;6,6,NWTJP-6,Northwind Traders Boysenberry Spread,18.7500,25.00,25,100,12 - 8 oz jars,0,25.0,"Jams, Preserves",False

#### 2.4. Identify Duplicated Observations

In [19]:
df[df.duplicated(subset='product_code', keep=False) == True]

,supplier_ids,id,product_code,product_name,standard_cost,list_price,reorder_level,target_level,quantity_per_unit,discontinued,minimum_reorder_quantity,category,discontinued_desc
4,2;6,6,NWTJP-6,Northwind Traders Boysenberry Spread,18.75,25.0,25,100,12 - 8 oz jars,0,25.0,"Jams, Preserves",False
10,2;6,20,NWTJP-6,Northwind Traders Marmalade,60.75,81.0,10,40,30 gift boxes,0,10.0,"Jams, Preserves",False
28,1,82,NWTC-82,Northwind Traders Granola,2.00,4.0,20,100,NaN,0,NaN,Cereal,False
42,1,97,NWTC-82,Northwind Traders Hot Cereal,3.00,5.0,50,200,NaN,0,NaN,Cereal,False

#### 2.5. Write the Contents of the DataFrame to a New JavaScript Object Notation (JSON) File

In [20]:
new_file = os.path.join(data_dir, 'northwind_products_cleaned.json')
df.to_json(new_file)

#### 2.6. Open the New JavaScript Object Notation (JSON) File to Verify the Data

In [21]:
df = pd.read_json(new_file)
df.head()

,supplier_ids,id,product_code,product_name,standard_cost,list_price,reorder_level,target_level,quantity_per_unit,discontinued,minimum_reorder_quantity,category,discontinued_desc
0,4,1,NWTB-1,Northwind Traders Chai,13.5000,18.00,10,40,10 boxes x 20 bags,0,10.0,Beverages,False
1,10,3,NWTCO-3,Northwind Traders Syrup,7.5000,10.00,25,100,12 - 550 ml bottles,0,25.0,Condiments,False
2,10,4,NWTCO-4,Northwind Traders Cajun Seasoning,16.5000,22.00,10,40,48 - 6 oz jars,0,10.0,Condiments,False
3,10,5,NWTO-5,Northwind Traders Olive Oil,16.0125,21.35,10,40,36 boxes,0,10.0,Oil,False
4,2;6,6,NWTJP-6,Northwind Traders Boysenberry Spread,18.7500,25.00,25,100,12 - 8 oz jars,0,25.0,"Jams, Preserves",False